# Generated by Django 5.2.10 on 2026-09-25 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='setup.project'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_state_code_when_set'),
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='setup.state'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='unique_area_name_per_district'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('district', 'code'), name='unique_area_code_per_district'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('area', 'name'), name='unique_project_name_per_area'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('area', 'code'), name='unique_project_code_per_area'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='unique_district_name_per_region'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('region', 'code'), name='unique_district_code_per_region'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_site_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('project', 'code'), name='unique_site_code_per_project'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='unique_region_name_per_state'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('state', 'code'), name='unique_region_code_per_state'),
        ),
    ]
