# Generated by Django 5.2.10 on 2026-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=64, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('market_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('current_market_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='active', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['property_id'],
            },
        ),
        migrations.CreateModel(
            name='PropertySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('inserted', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
    ]
